spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dd_backend
    password: Longyizhou2001
    username: root
    initialization-mode: always
#    schema: classpath:/Sql/*.sql
#  jpa:
#    hibernate:
#      ddl-auto: create
mybatis:
  mapper-locations:
    - classpath:Mapper/zzy/*.xml
    - classpath:Mapper/lyz/*.xml
    - classpath:Mapper/yyh/*.xml
  type-aliases-package: diamondpick.dd_backend.Entity
server:
  port: 8080