spring:
  datasource:
    url: jdbc:mysql://43.138.71.108:3306/dd_backend
    #    password: diamond
    username: diamond
#    initialization-mode:
#    schema: classpath:/Sql/*.sql
#  jpa:
#    hibernate:
#      ddl-auto: create
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  #    - classpath:Mapper/zzy/*.xml
  #    - classpath:Mapper/lyz/*.xml
  #    - classpath:Mapper/yyh/*.xml
  type-aliases-package: diamondpick.dd_backend.Entity
server:
  port: 80