spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DD_backend
    password: Longyizhou2001
    username: root
  jpa:
    hibernate:
      ddl-auto: update
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: diamondpick.dd_backend.Entity
server:
  port: 8080