name: Java CI with Maven

on:
  push:
    # 分支
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Running Java ${{ matrix.java }} compile
    steps:
      - name: 在服务器上执行 java -jar，请确保服务器安装了 JDK
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: | # 命令中的 & 表示在后台运行进程
            cd ~/DD_backend/
            sudo git checkout master
            sudo git fetch --all 
            sudo git reset --hard origin/master
            sudo git pull
            sudo mvn install
            sudo mvn -B package --file pom.xml -Dmaven.test.skip=true 
            sudo fuser -k 8080/tcp
            sudo java -jar target/DD_backend-0.0.1-SNAPSHOT.jar &
          host: ${{ secrets.HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          args: "-tt"